### ISSUE TITLE
->getRateLimitRemaining() returns 'unknown'

### ISSUE THREAD

**Issue by gordielachance** [dirkgroenen/Pinterest-API-PHP#70] opened 2017-09-28 10:56 UTC
Hi, 
_->getRateLimit()_ works;
but
_->getRateLimitRemaining()_ returns unknown...

**Comment by dirkgroenen** [comment] 2017-10-29 12:28
Hmm that's weird, `getRateLimit()` and `getRateLimitRemaining()` both use the same mechanism to fetch the header which gives us that information. Just confirmed with the Pinterest API Docs and nothing seems to have changed.

I'm not in the position right now to actually check it, but code-wise is should work.

Is there any additional information you can provide?

**Comment by zigstum** [comment] 2017-11-16 15:27
dumping the $header var in the two appropriate functions in Pinterest.php shows that no headers are being returned - ie. the $header var comes up null.

It seems that the getRateLimit is working because it is a default value of 1000 if no header exists:
`return (isset($header['X-Ratelimit-Limit']) ? $header['X-Ratelimit-Limit'] : 1000);`

So, neither of those functions are actually working.

**Comment by dirkgroenen** [comment] 2017-11-16 16:26
Interesting, thanks @zigstum. 
Feel free to open a PR if you feel like solving this. Otherwise I'll see if I can make some time soon to fix it.

**Comment by zigstum** [comment] 2017-11-16 18:45
Running the API call through 'Postman' shows that the headers are present in the response:

```
Access-Control-Allow-Origin →*
Age →0
Cache-Control →private
Connection →keep-alive
Content-Length →131
Content-Type →application/json
Date →Thu, 16 Nov 2017 17:49:17 GMT
Pinterest-Generated-By →
Pinterest-Version →1294124
X-Content-Type-Options →nosniff
X-Pinterest-RID →XXXX
X-Ratelimit-Limit →200
X-Ratelimit-Remaining →25
```

Dumping the value of `$this->headers` in Request.php shows that the headers do exist:
```
// Get headers from last request
        $this->headers = $ch->getHeaders();

// this gives:

array:16 [
  0 => "HTTP/1.1 200 OK\r"
  "Access-Control-Allow-Origin" => "*"
  "Age" => "0"
  "Cache-Control" => "private"
  "Content-Type" => "application/json"
  "Pinterest-Version" => "1294124"
  "X-Content-Type-Options" => "nosniff"
  "X-Pinterest-RID" => "XXXX"
  "X-Ratelimit-Limit" => "200"
  "X-Ratelimit-Remaining" => "159"
  "Content-Length" => "369"
  "Date" => "Thu, 16 Nov 2017 18:43:01 GMT"
  "Connection" => "keep-alive"
  "Pinterest-Generated-By" => ""
  1 => "\r"
  2 => ""
]
```

So, the headers are received, but they are not propagating to the function that is called.

**Comment by sfatfarma** [comment] 2017-12-13 12:34
Hello,

First of all, thank you for the great API.

Found the same issue myself, getRateLimitRemaining() returns unknown.

Also, I got rate limited today, so this info would be great to have. :)

Regards,
Szabi.

**Comment by sfatfarma** [comment] 2017-12-13 13:40
Well, I have investigated a bit more on this issue, and it seems that getRateLimitRemaining() works, but only if you make a direct API call to any endpoint, before calling it. 

So, if you initialize the framework and immediately check getRateLimitRemaining(), it will return 'unknown'.

**Comment by dirkgroenen** [comment] 2018-01-09 09:30
Seems like the correct headers are used (`X-Ratelimit-Remaining`). Anybody who can confirm this is indeed a code issue, or if it's related to @sfatfarma's explanation?

**Comment by dirkgroenen** [comment] 2018-06-01 09:09
The `getRateLimitRemaining()` method uses the headers from its last made request. If you initialize the framework and immediately check the remaining limit you will indeed get the `unknown` value. 

I guess this could be improved in the documentation, or maybe add something to the `unknown` value so users know that they should make a request first.

**Comment by sfatfarma** [comment] 2018-06-02 05:36
Thank you for the explanations. :)

**Comment by cheekyboots** [comment] 2018-12-31 03:59
I had the same problem. I fixed it with a change to capitalization. The headers I got were this:

X-RateLimit...

In the code it has:
X-Ratelimit...

The lowercase L is correct according to Pinterest documentation, but not according to what actually got returned when dumping  $pinterest->request;

**Comment by cheekyboots** [comment] 2019-01-03 02:12
Actually it seems like it is sometimes one and sometimes the other, so you have to check both.

**Comment by dirkgroenen** [comment] 2019-06-14 08:28
This will be in release [0.2.12](https://github.com/dirkgroenen/Pinterest-API-PHP/pull/102)

**Closed by dirkgroenen** 2019-06-14 08:28 UTC
