### ISSUE TITLE
can't pin an image to Pinterest but no error sent

### ISSUE THREAD

**Issue by TaktakTaktouk** [dirkgroenen/Pinterest-API-PHP#112] opened 2020-02-27 17:03 UTC
I'm using the same code since 2017, every day it shares some GIFs automatically, but since 27/01 it stopped working, but I don't see any error. Does Pinterest change something?
here is my code:
`$pin = $pinterest->pins->create(array(
				"note"          => "test"
				"image_url"     => "test.gif",
				"board"         => "keepgif/lol",
				"link"			=> "url"
		));`

**Comment by dirkgroenen** [comment] 2020-03-02 07:30
Are you using the latest version (0.2.13)?

**Comment by dirkgroenen** [comment] 2020-03-11 22:32
I've tried reproducing this using the latest demo in `master` but it all seems to be working fine for me. Please check if you're using the latest version. 

I'll close this for now, but feel free to re-open when you keep on experiencing the same issue. Also make sure to share a reproducible repo.

**Closed by dirkgroenen** 2020-03-11 22:32 UTC

**Comment by waqasd4int** [comment] 2020-03-17 11:30
hi @dirkgroenen I am still facing this issue and this issue is generated 7271 times on my end i have the payload in the logs can you please fix this issue.

**Comment by dirkgroenen** [comment] 2020-03-17 11:32
@waqasd4int As mentioned I wasn't able to reproduce this myself when using the latest master branch. Can you provide me with a repository which reproduces this issue?

**Comment by waqasd4int** [comment] 2020-03-17 11:35
@dirkgroenen it is not happening in all cases it is generating in some specific case I am also not able to reproduce this issue but I check in the logs it is still generating for some of the pins

**Comment by TaktakTaktouk** [comment] 2020-03-17 11:40
issue fixed after updating to the latest version (0.2.13)
